[package]
name = "wasi-versions"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.40.0", features = ["macros", "rt", "net"] }

[patch.crates-io]
tokio = { git = "https://github.com/dicej/tokio", branch = "wasip2" }
